# Python Prerequisites: 04. Data Handling Basics

Practical implementation of feature matrix ($X$), target vector ($y$), and train-test splits.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# 1. Realistic Dataset
df = pd.DataFrame({
    'Age': [25, 30, 45, 35, 23, 40, 32, 48, 28, 55],
    'Salary': [50000, 70000, 120000, 85000, 35000, 85000, 60000, 110000, 54000, 140000],
    'Purchased': [0, 1, 1, 0, 0, 1, 0, 1, 0, 1]
})

print("--- Full Dataset ---")
display(df)

--- Full Dataset ---

   Age  Salary  Purchased
0   25   50000          0
1   30   70000          1
2   45  120000          1
3   35   85000          0
4   23   35000          0
5   40   85000          1
6   32   60000          0
7   48  110000          1
8   28   54000          0
9   55  140000          1

In [2]:
# 2. Separating Features (X) and Target (y)
# X must be a 2D matrix (uppercase X)
X = df[['Age', 'Salary']]

# y is a 1D vector (lowercase y)
y = df['Purchased']

print("Features X shape:", X.shape)
print("Target y shape:  ", y.shape)

Features X shape: (10, 2)
Target y shape:   (10,)

In [3]:
# 3. Train-Test Split (Preventing Overfitting)
# 80% train, 20% test, with fixed random seed
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

print(f"X_train samples: {len(X_train)} | X_test samples: {len(X_test)}")
print("\nTraining Features:")
display(X_train)
print("\nTest Features (Held out for evaluation!):")
display(X_test)

X_train samples: 8 | X_test samples: 2

Training Features:

   Age  Salary
5   40   85000
0   25   50000
7   48  110000
2   45  120000
9   55  140000
4   23   35000
3   35   85000
6   32   60000

Test Features (Held out for evaluation!):

   Age  Salary
8   28   54000
1   30   70000

In [4]:
# 4. Preventing Data Leakage Principle
# Learn statistics strictly on X_train!
train_mean_salary = X_train['Salary'].mean()
print(f"Train Mean Salary: ${train_mean_salary:,.2f}")

# Never compute statistics across the full dataset before splitting!

Train Mean Salary: $85,625.00