# Python Prerequisites: 03. Pandas Basics

Practical implementation of Pandas Series, DataFrames, indexing, filtering, and missing values.

In [1]:
import pandas as pd
import numpy as np

# 1. Creating Series and DataFrame
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25.0, 30.0, np.nan, 35.0],
    'Salary': [50000.0, 70000.0, 60000.0, 85000.0],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Bangalore'],
    'Purchased': [0, 1, 0, 1]
})

print("--- DataFrame Inspection ---")
display(df)
print("\nData Types:")
print(df.dtypes)

--- DataFrame Inspection ---

      Name   Age   Salary       City  Purchased
0    Alice  25.0  50000.0      Delhi          0
1      Bob  30.0  70000.0     Mumbai          1
2  Charlie   NaN  60000.0      Delhi          0
3    David  35.0  85000.0  Bangalore          1

Data Types:
Name          object
Age          float64
Salary       float64
City          object
Purchased      int64
dtype: object

In [2]:
# 2. Selecting Columns and Rows
# Single column (Series)
print("Ages Series:\n", df['Age'])

# Multiple columns (DataFrame)
print("\nSubset DataFrame:")
display(df[['Name', 'Salary']])

# Row indexing via iloc (by position)
print("\nRow 0:", df.iloc[0]['Name'])

Ages Series:
 0    25.0
1    30.0
2     NaN
3    35.0
Name: Age, dtype: float64

Subset DataFrame:

      Name   Salary
0    Alice  50000.0
1      Bob  70000.0
2  Charlie  60000.0
3    David  85000.0

Row 0: Alice

In [3]:
# 3. Filtering Rows with Boolean Conditions
high_earners = df[df['Salary'] >= 65000]
print("Employees earning >= $65,000:")
display(high_earners)

Employees earning >= $65,000:

    Name   Age   Salary       City  Purchased
1    Bob  30.0  70000.0     Mumbai          1
3  David  35.0  85000.0  Bangalore          1

In [4]:
# 4. Missing Value Detection and Imputation
print("Missing values count per column:")
print(df.isnull().sum())

# Fill missing Age with median
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)
print(f"\nFilled missing Age with median ({median_age}):")
display(df)

Missing values count per column:
Name         0
Age          1
Salary       0
City         0
Purchased    0
dtype: int64

Filled missing Age with median (30.0):

      Name   Age   Salary       City  Purchased
0    Alice  25.0  50000.0      Delhi          0
1      Bob  30.0  70000.0     Mumbai          1
2  Charlie  30.0  60000.0      Delhi          0
3    David  35.0  85000.0  Bangalore          1

In [5]:
# 5. Summary Statistics and GroupBy
print("--- Numerical Summary ---")
display(df.describe())

print("\nAverage Salary by City:")
print(df.groupby('City')['Salary'].mean())

--- Numerical Summary ---

             Age        Salary  Purchased
count   4.000000      4.000000    4.00000
mean   30.000000  66250.000000    0.50000
std     4.082483  14930.394056    0.57735
min    25.000000  50000.000000    0.00000
25%    28.750000  57500.000000    0.00000
50%    30.000000  65000.000000    0.50000
75%    31.250000  73750.000000    1.00000
max    35.000000  85000.000000    1.00000

Average Salary by City:
City
Bangalore    85000.0
Delhi        55000.0
Mumbai       70000.0
Name: Salary, dtype: float64